from setuptools import setup

setup(
	name='vmreact',
	version='0',
	packages=['venv.lib.python2.7.distutils', 'venv.lib.python2.7.encodings', 'venv.lib.python2.7.site-packages.pip',
			  'venv.lib.python2.7.site-packages.pip._vendor', 'venv.lib.python2.7.site-packages.pip._vendor.idna',
			  'venv.lib.python2.7.site-packages.pip._vendor.pytoml',
			  'venv.lib.python2.7.site-packages.pip._vendor.certifi',
			  'venv.lib.python2.7.site-packages.pip._vendor.chardet',
			  'venv.lib.python2.7.site-packages.pip._vendor.chardet.cli',
			  'venv.lib.python2.7.site-packages.pip._vendor.distlib',
			  'venv.lib.python2.7.site-packages.pip._vendor.distlib._backport',
			  'venv.lib.python2.7.site-packages.pip._vendor.msgpack',
			  'venv.lib.python2.7.site-packages.pip._vendor.urllib3',
			  'venv.lib.python2.7.site-packages.pip._vendor.urllib3.util',
			  'venv.lib.python2.7.site-packages.pip._vendor.urllib3.contrib',
			  'venv.lib.python2.7.site-packages.pip._vendor.urllib3.contrib._securetransport',
			  'venv.lib.python2.7.site-packages.pip._vendor.urllib3.packages',
			  'venv.lib.python2.7.site-packages.pip._vendor.urllib3.packages.backports',
			  'venv.lib.python2.7.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
			  'venv.lib.python2.7.site-packages.pip._vendor.colorama',
			  'venv.lib.python2.7.site-packages.pip._vendor.html5lib',
			  'venv.lib.python2.7.site-packages.pip._vendor.html5lib._trie',
			  'venv.lib.python2.7.site-packages.pip._vendor.html5lib.filters',
			  'venv.lib.python2.7.site-packages.pip._vendor.html5lib.treewalkers',
			  'venv.lib.python2.7.site-packages.pip._vendor.html5lib.treeadapters',
			  'venv.lib.python2.7.site-packages.pip._vendor.html5lib.treebuilders',
			  'venv.lib.python2.7.site-packages.pip._vendor.lockfile',
			  'venv.lib.python2.7.site-packages.pip._vendor.progress',
			  'venv.lib.python2.7.site-packages.pip._vendor.requests',
			  'venv.lib.python2.7.site-packages.pip._vendor.packaging',
			  'venv.lib.python2.7.site-packages.pip._vendor.cachecontrol',
			  'venv.lib.python2.7.site-packages.pip._vendor.cachecontrol.caches',
			  'venv.lib.python2.7.site-packages.pip._vendor.webencodings',
			  'venv.lib.python2.7.site-packages.pip._vendor.pkg_resources',
			  'venv.lib.python2.7.site-packages.pip._internal', 'venv.lib.python2.7.site-packages.pip._internal.req',
			  'venv.lib.python2.7.site-packages.pip._internal.vcs',
			  'venv.lib.python2.7.site-packages.pip._internal.utils',
			  'venv.lib.python2.7.site-packages.pip._internal.models',
			  'venv.lib.python2.7.site-packages.pip._internal.commands',
			  'venv.lib.python2.7.site-packages.pip._internal.operations', 'venv.lib.python2.7.site-packages.enum',
			  'venv.lib.python2.7.site-packages.numpy', 'venv.lib.python2.7.site-packages.numpy.ma',
			  'venv.lib.python2.7.site-packages.numpy.ma.tests', 'venv.lib.python2.7.site-packages.numpy.doc',
			  'venv.lib.python2.7.site-packages.numpy.fft', 'venv.lib.python2.7.site-packages.numpy.fft.tests',
			  'venv.lib.python2.7.site-packages.numpy.lib', 'venv.lib.python2.7.site-packages.numpy.lib.tests',
			  'venv.lib.python2.7.site-packages.numpy.core', 'venv.lib.python2.7.site-packages.numpy.core.tests',
			  'venv.lib.python2.7.site-packages.numpy.f2py', 'venv.lib.python2.7.site-packages.numpy.f2py.tests',
			  'venv.lib.python2.7.site-packages.numpy.tests', 'venv.lib.python2.7.site-packages.numpy.compat',
			  'venv.lib.python2.7.site-packages.numpy.compat.tests', 'venv.lib.python2.7.site-packages.numpy.linalg',
			  'venv.lib.python2.7.site-packages.numpy.linalg.tests', 'venv.lib.python2.7.site-packages.numpy.random',
			  'venv.lib.python2.7.site-packages.numpy.random.tests', 'venv.lib.python2.7.site-packages.numpy.testing',
			  'venv.lib.python2.7.site-packages.numpy.testing.tests',
			  'venv.lib.python2.7.site-packages.numpy.testing._private',
			  'venv.lib.python2.7.site-packages.numpy.distutils',
			  'venv.lib.python2.7.site-packages.numpy.distutils.tests',
			  'venv.lib.python2.7.site-packages.numpy.distutils.command',
			  'venv.lib.python2.7.site-packages.numpy.distutils.fcompiler',
			  'venv.lib.python2.7.site-packages.numpy.matrixlib',
			  'venv.lib.python2.7.site-packages.numpy.matrixlib.tests',
			  'venv.lib.python2.7.site-packages.numpy.polynomial',
			  'venv.lib.python2.7.site-packages.numpy.polynomial.tests', 'venv.lib.python2.7.site-packages.wheel',
			  'venv.lib.python2.7.site-packages.wheel.tool', 'venv.lib.python2.7.site-packages.wheel.signatures',
			  'venv.lib.python2.7.site-packages.pandas', 'venv.lib.python2.7.site-packages.pandas.io',
			  'venv.lib.python2.7.site-packages.pandas.io.sas', 'venv.lib.python2.7.site-packages.pandas.io.json',
			  'venv.lib.python2.7.site-packages.pandas.io.formats',
			  'venv.lib.python2.7.site-packages.pandas.io.msgpack',
			  'venv.lib.python2.7.site-packages.pandas.io.clipboard', 'venv.lib.python2.7.site-packages.pandas.api',
			  'venv.lib.python2.7.site-packages.pandas.api.types',
			  'venv.lib.python2.7.site-packages.pandas.api.extensions', 'venv.lib.python2.7.site-packages.pandas.core',
			  'venv.lib.python2.7.site-packages.pandas.core.util', 'venv.lib.python2.7.site-packages.pandas.core.tools',
			  'venv.lib.python2.7.site-packages.pandas.core.arrays',
			  'venv.lib.python2.7.site-packages.pandas.core.dtypes',
			  'venv.lib.python2.7.site-packages.pandas.core.sparse',
			  'venv.lib.python2.7.site-packages.pandas.core.groupby',
			  'venv.lib.python2.7.site-packages.pandas.core.indexes',
			  'venv.lib.python2.7.site-packages.pandas.core.reshape',
			  'venv.lib.python2.7.site-packages.pandas.core.computation',
			  'venv.lib.python2.7.site-packages.pandas.util', 'venv.lib.python2.7.site-packages.pandas._libs',
			  'venv.lib.python2.7.site-packages.pandas._libs.tslibs', 'venv.lib.python2.7.site-packages.pandas.tests',
			  'venv.lib.python2.7.site-packages.pandas.tests.io',
			  'venv.lib.python2.7.site-packages.pandas.tests.io.sas',
			  'venv.lib.python2.7.site-packages.pandas.tests.io.json',
			  'venv.lib.python2.7.site-packages.pandas.tests.io.parser',
			  'venv.lib.python2.7.site-packages.pandas.tests.io.formats',
			  'venv.lib.python2.7.site-packages.pandas.tests.io.msgpack',
			  'venv.lib.python2.7.site-packages.pandas.tests.api', 'venv.lib.python2.7.site-packages.pandas.tests.util',
			  'venv.lib.python2.7.site-packages.pandas.tests.frame',
			  'venv.lib.python2.7.site-packages.pandas.tests.tools',
			  'venv.lib.python2.7.site-packages.pandas.tests.dtypes',
			  'venv.lib.python2.7.site-packages.pandas.tests.scalar',
			  'venv.lib.python2.7.site-packages.pandas.tests.scalar.period',
			  'venv.lib.python2.7.site-packages.pandas.tests.scalar.interval',
			  'venv.lib.python2.7.site-packages.pandas.tests.scalar.timedelta',
			  'venv.lib.python2.7.site-packages.pandas.tests.scalar.timestamp',
			  'venv.lib.python2.7.site-packages.pandas.tests.series',
			  'venv.lib.python2.7.site-packages.pandas.tests.series.indexing',
			  'venv.lib.python2.7.site-packages.pandas.tests.sparse',
			  'venv.lib.python2.7.site-packages.pandas.tests.sparse.frame',
			  'venv.lib.python2.7.site-packages.pandas.tests.sparse.series',
			  'venv.lib.python2.7.site-packages.pandas.tests.tslibs',
			  'venv.lib.python2.7.site-packages.pandas.tests.generic',
			  'venv.lib.python2.7.site-packages.pandas.tests.groupby',
			  'venv.lib.python2.7.site-packages.pandas.tests.groupby.aggregate',
			  'venv.lib.python2.7.site-packages.pandas.tests.indexes',
			  'venv.lib.python2.7.site-packages.pandas.tests.indexes.period',
			  'venv.lib.python2.7.site-packages.pandas.tests.indexes.interval',
			  'venv.lib.python2.7.site-packages.pandas.tests.indexes.datetimes',
			  'venv.lib.python2.7.site-packages.pandas.tests.indexes.timedeltas',
			  'venv.lib.python2.7.site-packages.pandas.tests.reshape',
			  'venv.lib.python2.7.site-packages.pandas.tests.reshape.merge',
			  'venv.lib.python2.7.site-packages.pandas.tests.tseries',
			  'venv.lib.python2.7.site-packages.pandas.tests.tseries.offsets',
			  'venv.lib.python2.7.site-packages.pandas.tests.indexing',
			  'venv.lib.python2.7.site-packages.pandas.tests.indexing.interval',
			  'venv.lib.python2.7.site-packages.pandas.tests.plotting',
			  'venv.lib.python2.7.site-packages.pandas.tests.extension',
			  'venv.lib.python2.7.site-packages.pandas.tests.extension.base',
			  'venv.lib.python2.7.site-packages.pandas.tests.extension.json',
			  'venv.lib.python2.7.site-packages.pandas.tests.extension.decimal',
			  'venv.lib.python2.7.site-packages.pandas.tests.extension.category',
			  'venv.lib.python2.7.site-packages.pandas.tests.internals',
			  'venv.lib.python2.7.site-packages.pandas.tests.categorical',
			  'venv.lib.python2.7.site-packages.pandas.tests.computation',
			  'venv.lib.python2.7.site-packages.pandas.tools', 'venv.lib.python2.7.site-packages.pandas.types',
			  'venv.lib.python2.7.site-packages.pandas.compat', 'venv.lib.python2.7.site-packages.pandas.compat.numpy',
			  'venv.lib.python2.7.site-packages.pandas.errors', 'venv.lib.python2.7.site-packages.pandas.formats',
			  'venv.lib.python2.7.site-packages.pandas.tseries', 'venv.lib.python2.7.site-packages.pandas.plotting',
			  'venv.lib.python2.7.site-packages.pandas.computation', 'venv.lib.python2.7.site-packages.appnope',
			  'venv.lib.python2.7.site-packages.IPython', 'venv.lib.python2.7.site-packages.IPython.lib',
			  'venv.lib.python2.7.site-packages.IPython.lib.tests', 'venv.lib.python2.7.site-packages.IPython.core',
			  'venv.lib.python2.7.site-packages.IPython.core.tests',
			  'venv.lib.python2.7.site-packages.IPython.core.magics', 'venv.lib.python2.7.site-packages.IPython.utils',
			  'venv.lib.python2.7.site-packages.IPython.utils.tests', 'venv.lib.python2.7.site-packages.IPython.kernel',
			  'venv.lib.python2.7.site-packages.IPython.testing',
			  'venv.lib.python2.7.site-packages.IPython.testing.tests',
			  'venv.lib.python2.7.site-packages.IPython.testing.plugin',
			  'venv.lib.python2.7.site-packages.IPython.external',
			  'venv.lib.python2.7.site-packages.IPython.external.decorators',
			  'venv.lib.python2.7.site-packages.IPython.terminal',
			  'venv.lib.python2.7.site-packages.IPython.terminal.tests',
			  'venv.lib.python2.7.site-packages.IPython.terminal.pt_inputhooks',
			  'venv.lib.python2.7.site-packages.IPython.sphinxext',
			  'venv.lib.python2.7.site-packages.IPython.extensions',
			  'venv.lib.python2.7.site-packages.IPython.extensions.tests', 'venv.lib.python2.7.site-packages.pexpect',
			  'venv.lib.python2.7.site-packages.wcwidth', 'venv.lib.python2.7.site-packages.wcwidth.tests',
			  'venv.lib.python2.7.site-packages.dateutil', 'venv.lib.python2.7.site-packages.dateutil.zoneinfo',
			  'venv.lib.python2.7.site-packages.pathlib2', 'venv.lib.python2.7.site-packages.pygments',
			  'venv.lib.python2.7.site-packages.pygments.lexers', 'venv.lib.python2.7.site-packages.pygments.styles',
			  'venv.lib.python2.7.site-packages.pygments.filters',
			  'venv.lib.python2.7.site-packages.pygments.formatters', 'venv.lib.python2.7.site-packages.backports',
			  'venv.lib.python2.7.site-packages.backports.shutil_get_terminal_size',
			  'venv.lib.python2.7.site-packages.traitlets', 'venv.lib.python2.7.site-packages.traitlets.tests',
			  'venv.lib.python2.7.site-packages.traitlets.utils',
			  'venv.lib.python2.7.site-packages.traitlets.utils.tests',
			  'venv.lib.python2.7.site-packages.traitlets.config',
			  'venv.lib.python2.7.site-packages.traitlets.config.tests', 'venv.lib.python2.7.site-packages.ptyprocess',
			  'venv.lib.python2.7.site-packages.setuptools', 'venv.lib.python2.7.site-packages.setuptools.extern',
			  'venv.lib.python2.7.site-packages.setuptools._vendor',
			  'venv.lib.python2.7.site-packages.setuptools._vendor.packaging',
			  'venv.lib.python2.7.site-packages.setuptools.command', 'venv.lib.python2.7.site-packages.pkg_resources',
			  'venv.lib.python2.7.site-packages.pkg_resources.extern',
			  'venv.lib.python2.7.site-packages.pkg_resources._vendor',
			  'venv.lib.python2.7.site-packages.pkg_resources._vendor.packaging',
			  'venv.lib.python2.7.site-packages.prompt_toolkit',
			  'venv.lib.python2.7.site-packages.prompt_toolkit.layout',
			  'venv.lib.python2.7.site-packages.prompt_toolkit.styles',
			  'venv.lib.python2.7.site-packages.prompt_toolkit.contrib',
			  'venv.lib.python2.7.site-packages.prompt_toolkit.contrib.telnet',
			  'venv.lib.python2.7.site-packages.prompt_toolkit.contrib.completers',
			  'venv.lib.python2.7.site-packages.prompt_toolkit.contrib.validators',
			  'venv.lib.python2.7.site-packages.prompt_toolkit.contrib.regular_languages',
			  'venv.lib.python2.7.site-packages.prompt_toolkit.filters',
			  'venv.lib.python2.7.site-packages.prompt_toolkit.terminal',
			  'venv.lib.python2.7.site-packages.prompt_toolkit.clipboard',
			  'venv.lib.python2.7.site-packages.prompt_toolkit.eventloop',
			  'venv.lib.python2.7.site-packages.prompt_toolkit.key_binding',
			  'venv.lib.python2.7.site-packages.prompt_toolkit.key_binding.bindings',
			  'venv.lib.python2.7.site-packages.ipython_genutils',
			  'venv.lib.python2.7.site-packages.ipython_genutils.tests',
			  'venv.lib.python2.7.site-packages.ipython_genutils.testing',
			  'venv.lib.python2.7.site-packages.shutil_backports'],
	url='',
	license='',
	author='dawlat el-said',
	author_email='daelsaid@stanford.edu',
	description='vmreact package'
)
